Add getTableNameById method
Backendless/JS-SDK pull request #226
Opened 2022-02-09 21:22 UTC by viktor-liablin

Add getTableNameById method

2022-02-09 21:28 UTC, stanislav-grin requested changes

2022-02-09 21:28 UTC, stanislav-grin commented on backendless.d.ts
> +        function getTableNameById(model: string): Promise<Object>;
why model? Should be `tableId`

2022-02-09 21:34 UTC, viktor-liablin commented on backendless.d.ts
> +        function getTableNameById(model: string): Promise<Object>;
done

2022-02-10 15:48 UTC, Valodya commented on backendless.d.ts
> +        function getTableNameById(tableId: string): Promise<Object>;
does it return an `Object` or `String`?

2022-02-10 20:27 UTC, viktor-liablin commented on backendless.d.ts
> +        function getTableNameById(tableId: string): Promise<Object>;
done

2022-02-15 08:30 UTC, merged